# Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: #database connection pool
      connection-test-query: 'select 1'
      connection-timeout: 10000 # 10 sec.
      maximum-pool-size: 10
      pool-name: smarth-server-pool
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true# Database
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host : localhost
    port : 5672
    username : guest
    password : guest

sandbox:
  jwt-ttl: 360000000
  jwt-refresh-ttl: 360000000
  telegram-exception-message: y
  use-hmac: 0

